In [1]:
import numpy as np

In [148]:
class GameState (object):
    def __init__ (self, board=np.zeros(9, dtype=np.int8), player=1):
        self.board =  board
        self.player = player

    def get_legal_actions(self):
        actions = []
        if not self.is_game_over():
            actions, = np.where(self.board==0)
        return actions

    def is_game_over(self):
        # check if board is full
        if 0 not in self.board:
            return True
        # check if anyone won
        elif self.game_result() != 0:
            return True
        return False
    
    def game_result(self):
        board = self.board.reshape((3,3))
        # check rows
        for i in range(3):
            value = int(np.sum(board[i,:])/3)
            if np.absolute(value) == 1:
                return value         
        # check columns
        for i in range(3):
            value = int(np.sum(board[:,i])/3)
            if np.absolute(value) == 1:
                return value    
        # check diagonal 1
        value = int((board[0][0] + board[1][1] + board[2][2])/3)
        if np.absolute(value) == 1:
            return value
        # check diagonal 2
        value = int((board[0][2] + board[1][1] + board[2][0])/3)
        if np.absolute(value) == 1:
            return value
        # otherwise it's a tie
        return 0
    
    def move(self, action):
        if action in self.get_legal_actions():
            self.board[action] = self.player
            self.player = -self.player
        else:
            print("ERROR: action passed to move is not legal!")
            
    def select_random_action(self):
        return np.random.choice(state.get_legal_actions())

    def get_board(self):
        return self.board

    def get_player(self):
        return self.player

    def __eq__(self, other):
        return ((np.array_equal(self.board, other.board)) and (self.player == other.player))

    def __ne__(self, other):
        return not self.__eq__(other)

In [10]:
from Game import*
# state = GameState(board=np.zeros(9, dtype=np.int8), player=1)
state = GameState()
state.new_game()
print("GAME\n")
print(state.get_board().reshape((3,3)))
while not state.is_game_over():
    action = state.select_random_action()
    print("\nPlayer to play: %d" % (state.get_player()))
    print("Chosen move:    %d\n" % (action))
    state.move(action)
    print(state.get_board().reshape((3,3)))
print("\nGame result: %d" % (state.game_result()))

GAME

[[0 0 0]
 [0 0 0]
 [0 0 0]]

Player to play: 1
Chosen move:    4

[[0 0 0]
 [0 1 0]
 [0 0 0]]

Player to play: -1
Chosen move:    1

[[ 0 -1  0]
 [ 0  1  0]
 [ 0  0  0]]

Player to play: 1
Chosen move:    7

[[ 0 -1  0]
 [ 0  1  0]
 [ 0  1  0]]

Player to play: -1
Chosen move:    2

[[ 0 -1 -1]
 [ 0  1  0]
 [ 0  1  0]]

Player to play: 1
Chosen move:    3

[[ 0 -1 -1]
 [ 1  1  0]
 [ 0  1  0]]

Player to play: -1
Chosen move:    6

[[ 0 -1 -1]
 [ 1  1  0]
 [-1  1  0]]

Player to play: 1
Chosen move:    8

[[ 0 -1 -1]
 [ 1  1  0]
 [-1  1  1]]

Player to play: -1
Chosen move:    0

[[-1 -1 -1]
 [ 1  1  0]
 [-1  1  1]]

Game result: -1
